# Generated by Django 4.1.13 on 2024-05-13 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('identificacion', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_Contratacion',
            fields=[
                ('nombre', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_Empleado',
            fields=[
                ('nombre', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sedes',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('cod_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.ciudades')),
            ],
        ),
        migrations.CreateModel(
            name='Programas',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('cod_areas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.areas')),
            ],
        ),
        migrations.CreateModel(
            name='Facultades',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(max_length=15)),
                ('nro_telefono', models.CharField(max_length=15)),
                ('id_decano', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.empleados')),
            ],
        ),
        migrations.AddField(
            model_name='empleados',
            name='cod_facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.facultades'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='cod_sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.sedes'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='lugar_nacimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.ciudades'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='tipo_contratacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.tipos_contratacion'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='tipo_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.tipos_empleado'),
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('cod_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.paises')),
            ],
        ),
        migrations.AddField(
            model_name='ciudades',
            name='cod_dpto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.departamentos'),
        ),
        migrations.AddField(
            model_name='areas',
            name='codigo_facultades',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.facultades'),
        ),
        migrations.AddField(
            model_name='areas',
            name='id_coordinador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.empleados'),
        ),
    ]
