# Generated by Django 5.0.6 on 2024-05-07 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_Contratacion',
            fields=[
                ('nombre', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_Empleado',
            fields=[
                ('nombre', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cuidades',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('cod_dpto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.departamentos')),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('identificacion', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('lugar_nacimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.cuidades')),
            ],
        ),
        migrations.CreateModel(
            name='Facultades',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(max_length=15)),
                ('nro_telefono', models.CharField(max_length=15)),
                ('id_decano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.empleados')),
            ],
        ),
        migrations.AddField(
            model_name='empleados',
            name='cod_facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.facultades'),
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('id_coordinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.empleados')),
                ('codigo_facultades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.facultades')),
            ],
        ),
        migrations.AddField(
            model_name='departamentos',
            name='cod_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.paises'),
        ),
        migrations.CreateModel(
            name='Programas',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('cod_areas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.areas')),
            ],
        ),
        migrations.CreateModel(
            name='Sedes',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('cod_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.cuidades')),
            ],
        ),
        migrations.AddField(
            model_name='empleados',
            name='cod_sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.sedes'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='tipo_contratacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.tipos_contratacion'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='tipo_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.tipos_empleado'),
        ),
    ]
