# Generated by Django 4.1.13 on 2024-05-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('identificacion', models.CharField(max_length=15, unique=True)),
                ('tipo_relacion', models.CharField(choices=[('profesor', 'profesor'), ('estudiante', 'estudiante'), ('graduado', 'graduado'), ('empresario', 'empresario'), ('administrativo', 'administrativo'), ('directivo', 'directivo')], max_length=20)),
                ('nombre_usuario', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('ciudad', models.IntegerField()),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuthenticationCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
                ('codigo', models.CharField(max_length=6)),
            ],
        ),
    ]
